### PR TITLE
whitelist: Fix Lineagehw permissions

### PR DESCRIPTION
**Pull request by ghost**
Got bootloop without these permissions

log:
E Zygote  : java.lang.IllegalStateException: Signature|privileged
permissions not in privapp-permissions whitelist: {com.android.settings
(/system/system_ext/priv-app/Settings):
lineageos.permission.MANAGE_LIVEDISPLAY, com.android.systemui
(/system/system_ext/priv-app/SystemUI):
lineageos.permission.HARDWARE_ABSTRACTION_ACCESS, com.android.systemui
(/system/system_ext/priv-app/SystemUI):
lineageos.permission.MANAGE_LIVEDISPLAY}

permissions added, rom boots fine.

### CODE REVIEW

**Comment by Haxk20** [comment]
I have the same issue but this PR seems to be incorrect after having a chat with Mohan.

The permissions are already defined here: https://github.com/DotOS/android_vendor_dot/blob/dot11/config/permissions/privapp-permissions-lineagehw.xml

But somehow arent getting allowed for some devices.

**Comment by Haxk20** [comment]
Ah i see the issue. The permissions are applied but they apply only to product packages and do not touch system_ext packages where systemUI and settings live.

**Comment by ghost** [comment]
> I have the same issue but this PR seems to be incorrect after having a chat with Mohan.
> 
> The permissions are already defined here: https://github.com/DotOS/android_vendor_dot/blob/dot11/config/permissions/privapp-permissions-lineagehw.xml
> 
> But somehow arent getting allowed for some devices.

Noticed, I told to Mohan too... I use this way to fix my bootloop? Try it, if you still not bootable, please tell me :)

**Comment by mohancm** [comment]
well, I have moved those permissions to the system_ext partition. 
https://review.droidontime.com/c/DotOS/android_vendor_dot/+/819

**Comment by Haxk20** [comment]
Ah great i can drop my changes from my repo then.

**Comment by ghost** [comment]
> well, I have moved those permissions to the system_ext partition.
> https://review.droidontime.com/c/DotOS/android_vendor_dot/+/819

Thanks, so I can close it now :)

**Pull request closed without merging**
